// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSM9eR4dhkFkvboUfmLyQ5Zn8c3DzjQh0',
    appId: '1:394838439647:web:77c88e23b846fb1fdb5b6a',
    messagingSenderId: '394838439647',
    projectId: 'manage-devices-4st',
    authDomain: 'manage-devices-4st.firebaseapp.com',
    storageBucket: 'manage-devices-4st.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjy3P8iJx0EnUa5f3fZW_dZ1Z4CCLa4R4',
    appId: '1:394838439647:android:cedd52994fb0ce7adb5b6a',
    messagingSenderId: '394838439647',
    projectId: 'manage-devices-4st',
    storageBucket: 'manage-devices-4st.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEp2punJWsmzDUEEg_ah-wWnKz45t5xbc',
    appId: '1:394838439647:ios:da3acdf4bc6c3e8edb5b6a',
    messagingSenderId: '394838439647',
    projectId: 'manage-devices-4st',
    storageBucket: 'manage-devices-4st.appspot.com',
    iosClientId: '394838439647-6nplrq777kishl850plov3fjijlb7rvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.manageDevicesApp',
  );
}
